updates to make more flexible

diff --git a/.github/actions/version-increment/action.yml b/.github/actions/version-increment/action.yml
--- a/.github/actions/version-increment/action.yml
+++ b/.github/actions/version-increment/action.yml
@@ -23,34 +23,35 @@ runs:
       run: |
         set -euo pipefail
 
-        LATEST_VERSION="$(gh release list --json tagName,isLatest --jq '.[] | select(.isLatest == true) | .tagName' | head -n1)"
-        LATEST_VERSION="${LATEST_VERSION#v}"
-
-        # Check if INCREMENT is 0, 1, or 2. If 2 check if the version has 3 parts, if not exit with error
+        # Check if INCREMENT is 0, 1, or 2.
         if [[ ! "${INCREMENT}" =~ ^[0-2]$ ]]; then
           echo "Increment field must be 0, 1, or 2"
           exit 1
         fi
-        if [[ "${INCREMENT}" -eq 2 && "$(echo "${LATEST_VERSION}" | awk -F. '{print NF}')" -ne 3 ]]; then
+
+        if LATEST_VERSION="$(gh release view --json tagName --jq '.tagName' 2>&1)"; then
+          LATEST_VERSION="${LATEST_VERSION#v}"
+        elif [[ "${LATEST_VERSION}" == "release not found" ]]; then
+          echo "No latest version found, setting next to 0.1"
+          NEXT_VERSION="0.1"
+          echo "version=${NEXT_VERSION}" >> "$GITHUB_OUTPUT"
+          exit 0
+        else
+          echo "Error fetching latest version: ${LATEST_VERSION}"
+          exit 1
+        fi
+
+        if [[ ! "${LATEST_VERSION}" =~ ^[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
+          echo "Latest version '${LATEST_VERSION}' is not in the expected format."
+          exit 1
+        fi
+
+        if [[ "${INCREMENT}" -eq 2 && "${LATEST_VERSION}" != *.*.* ]]; then
           echo "Cannot increment leftmost part of version '${LATEST_VERSION}' because it does not have 3 parts"
           exit 1
         fi
 
-        if [ -z "${LATEST_VERSION}" ]; then
-
-          echo "No latest version found, setting next to 0.1"
-          NEXT_VERSION="0.1"
-
-        elif [[ "${LATEST_VERSION}" =~ ^[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
-
-          NEXT_VERSION="$(echo "${LATEST_VERSION}" | awk -F. -v i="$INCREMENT" 'BEGIN{OFS="."} {$(NF-i)=$(NF-i)+1; print}')"
-          echo "Incrementing ${LATEST_VERSION} to ${NEXT_VERSION}"
-
-        else
-
-          echo "Latest version '${LATEST_VERSION}' is not in the expected format."
-          exit 1
-
-        fi
+        NEXT_VERSION="$(echo "${LATEST_VERSION}" | awk -F. -v i="$INCREMENT" 'BEGIN{OFS="."} {$(NF-i)=$(NF-i)+1; print}')"
+        echo "Incrementing ${LATEST_VERSION} to ${NEXT_VERSION}"
 
         echo "version=${NEXT_VERSION}" >> "$GITHUB_OUTPUT"
