updates

diff --git a/.github/actions/version-increment/action.yml b/.github/actions/version-increment/action.yml
--- a/.github/actions/version-increment/action.yml
+++ b/.github/actions/version-increment/action.yml
@@ -25,19 +25,25 @@ runs:
 
         # Check if INCREMENT is 0, 1, or 2.
         if [[ ! "${INCREMENT}" =~ ^[0-2]$ ]]; then
-          echo "Increment field must be 0, 1, or 2"
+          echo "Increment field must be 0, 1, or 2" >&2
           exit 1
         fi
 
         if LATEST_VERSION="$(gh release view --json tagName --jq '.tagName' 2>&1)"; then
           LATEST_VERSION="${LATEST_VERSION#v}"
         elif [[ "${LATEST_VERSION}" == "release not found" ]]; then
+
+          if [[ "${INCREMENT}" -ne 0 ]]; then
+            echo "Cannot use increment_field=${INCREMENT} when no release exists; initial version is '0.1'" >&2
+            exit 1
+          fi
+
           echo "No latest version found, setting next to 0.1"
           NEXT_VERSION="0.1"
           echo "version=${NEXT_VERSION}" >> "$GITHUB_OUTPUT"
           exit 0
         else
-          echo "Error fetching latest version: ${LATEST_VERSION}"
+          echo "Error fetching latest version: ${LATEST_VERSION}" >&2
           exit 1
         fi
 
@@ -47,7 +53,7 @@ runs:
         fi
 
         if [[ "${INCREMENT}" -eq 2 && "${LATEST_VERSION}" != *.*.* ]]; then
-          echo "Cannot increment leftmost part of version '${LATEST_VERSION}' because it does not have 3 parts"
+          echo "Cannot increment leftmost part of version '${LATEST_VERSION}' because it does not have 3 parts" >&2
           exit 1
         fi
 
